# Lab 01: Introduction to PyTorch

In [2]:
import torch

## PyTorch Tensors

In [3]:
x = torch.Tensor([5.3, 2.1, -3.1])
x

tensor([ 5.3000,  2.1000, -3.1000])

In [4]:
A = torch.Tensor([[5.3, 2.1],
                  [0.2, 2.1]])
A

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])

In [5]:
A = torch.rand(10, 2)
A

tensor([[0.6522, 0.6391],
        [0.7198, 0.1679],
        [0.6724, 0.0872],
        [0.9404, 0.7775],
        [0.9231, 0.3837],
        [0.6327, 0.0883],
        [0.6290, 0.9244],
        [0.5528, 0.4851],
        [0.6560, 0.3800],
        [0.6952, 0.7738]])

In [6]:
B = torch.randn(10, 2)
B

tensor([[ 0.7401,  1.9690],
        [-0.4568,  0.2272],
        [ 0.9017,  0.7247],
        [ 1.7088,  1.3311],
        [ 0.1317,  0.1736],
        [ 1.0294,  1.2069],
        [-1.4144,  1.2918],
        [-0.9225,  0.6411],
        [ 0.6150, -1.1030],
        [ 0.4886, -0.0897]])

In [7]:
A = torch.zeros(10, 2)
A

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
B = torch.rand(5, 2, 2)
B

tensor([[[0.4842, 0.8001],
         [0.2542, 0.6530]],

        [[0.7261, 0.0932],
         [0.2005, 0.0208]],

        [[0.6132, 0.4598],
         [0.1307, 0.4698]],

        [[0.6423, 0.3613],
         [0.7855, 0.0846]],

        [[0.6609, 0.3401],
         [0.6628, 0.3452]]])

In [9]:
B.size()

torch.Size([5, 2, 2])

In [10]:
B.dim()

3

In [11]:
B.type()

'torch.FloatTensor'

## Size and Dimension of a Tensor

In [12]:
A = torch.rand(3, 2, 2)
A

tensor([[[0.5121, 0.7209],
         [0.0208, 0.8555]],

        [[0.5743, 0.7460],
         [0.1445, 0.1887]],

        [[0.0551, 0.3392],
         [0.9003, 0.8385]]])

In [13]:
A.dim()

3

In [14]:
A.size(), A.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

## Adding and Multiplying Tensors

In [15]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = 2 * B
D = A + C
E = A * B

A, '\n', B, '\n', C, '\n', D, '\n', E

(tensor([[0.1732, 0.7041],
         [0.7589, 0.3700]]), '\n', tensor([[0.5235, 0.0926],
         [0.0490, 0.2750]]), '\n', tensor([[1.0471, 0.1852],
         [0.0979, 0.5500]]), '\n', tensor([[1.2202, 0.8893],
         [0.8569, 0.9199]]), '\n', tensor([[0.0907, 0.0652],
         [0.0372, 0.1017]]))

## Floats versus Integers

In [16]:
x = torch.Tensor([1.2, 2.5])
x, x.type()

(tensor([1.2000, 2.5000]), 'torch.FloatTensor')

In [17]:
y = torch.LongTensor([5, 6])
y, y.type()

(tensor([5, 6]), 'torch.LongTensor')

In [18]:
y = y.float()
y, y.type()

(tensor([5., 6.]), 'torch.FloatTensor')

In [19]:
x = x.long()
x, x.type()

(tensor([1, 2]), 'torch.LongTensor')

## Other Functions

In [20]:
x = torch.arange(10)
x, x.type()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'torch.LongTensor')

In [22]:
x = torch.range(1, 10)
x, x.type()

/Users/dongdongdongdong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 'torch.FloatTensor')

In [23]:
x = torch.randperm(10)
x, x.type()

(tensor([3, 6, 4, 8, 0, 5, 7, 9, 1, 2]), 'torch.LongTensor')

In [24]:
x = torch.arange(10).float()
x, x.type()

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 'torch.FloatTensor')

## Reshaping a Tensor

In [25]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
x.view(5, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [29]:
y = x[:6]
y

tensor([0, 1, 2, 3, 4, 5])

In [30]:
y = x.view(5, 2)
y[1:3]

tensor([[2, 3],
        [4, 5]])

In [31]:
idx = 1
n = 3

y[idx : idx+n]

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [32]:
y

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [34]:
a = y[4, 0]
a, a.dim(), a.size()

(tensor(8), 0, torch.Size([]))

In [38]:
b = a.item()
b

8

In [39]:
type(b)

int