# Lab 02: Manipulate PyTorch Tensors

In [1]:
import torch

### Q1: Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
A = torch.Tensor([[1, 2],
                  [3, 4]])

In [3]:
B = torch.Tensor([[10, 20], [30, 40]])

In [4]:
C = A + B
C

tensor([[11., 22.],
        [33., 44.]])

### Q2: Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [5]:
A.size(), A.dim(), A.type()

(torch.Size([2, 2]), 2, 'torch.FloatTensor')

### Q3: Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [7]:
A = A.long()
A

tensor([[1, 2],
        [3, 4]])

### Q4: Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [8]:
A = torch.rand(5, 2, 3)
A, A.type(), A.dim(), A.size(), A.size(1)

(tensor([[[0.5703, 0.4043, 0.2234],
          [0.8598, 0.6929, 0.2759]],
 
         [[0.1943, 0.8641, 0.0503],
          [0.9018, 0.1616, 0.7765]],
 
         [[0.0159, 0.1809, 0.1172],
          [0.3689, 0.9289, 0.3987]],
 
         [[0.2851, 0.9798, 0.4858],
          [0.3522, 0.6805, 0.4773]],
 
         [[0.8364, 0.7364, 0.2155],
          [0.2749, 0.5528, 0.8439]]]),
 'torch.FloatTensor',
 3,
 torch.Size([5, 2, 3]),
 2)

### Q5: Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [9]:
B = torch.zeros(2, 3, 4, 5)
B

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])