# Lab 01 : Linear Module - Exercise
## Inspecting a linear module

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Q1: Make a linear module  WITHOUT bias that takes input of size 2 and return output of size 3. 

In [2]:
mod = nn.Linear(2, 3, bias=False)
mod

Linear(in_features=2, out_features=3, bias=False)

### Q2: Print the internal parameters of the module. Try to print the bias and double check that it return you "None"

In [3]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[ 0.4980,  0.5215],
        [ 0.4049, -0.0878],
        [ 0.0307, -0.0655]], requires_grad=True)
None


### Q3: Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to your linear module. What is the output?

In [6]:
x = torch.Tensor([1, 1])
x

tensor([1., 1.])

In [7]:
y = mod(x)
y

tensor([ 1.0195,  0.3171, -0.0348], grad_fn=<SqueezeBackward3>)

### Q4: Change the internal parameters of your module so that the weights become $
W=\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
$. You need to write 6 lines, one per entry to be changed.

In [8]:
mod.weight[0, 0] = 1
mod.weight[0, 1] = 2
mod.weight[1, 0] = 3
mod.weight[1, 1] = 4
mod.weight[2, 0] = 5
mod.weight[2, 1] = 6

print(mod.weight)

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], grad_fn=<CopySlices>)


### Q5: Feed the vector $x$ to your module with updated parameters. What is the output? 

In [9]:
y2 = mod(x)
y2

tensor([ 3.,  7., 11.], grad_fn=<SqueezeBackward3>)

### Compute by hand $y=Wx$ and check that pytorch got it correctly. 

$$
\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
\begin{bmatrix}1\\1 \end{bmatrix}=
\begin{bmatrix}?\\? \\ ? \end{bmatrix}
$$