# Lab 03 : Vanilla Neural Networks - Demo

## Creating a two-layer network

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### In Python, networks are defined as classes

In [2]:
class two_layer_net(nn.Module):
    
    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size, bias=True)
        self.layer2 = nn.Linear(hidden_size, output_size, bias=True)
        
    def forward(self, x):
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        p = F.softmax(x, dim=0)
        return p

### Create an instance that takes input of size 2, then transform it into something of size 5, then into something of size 3
$$
\begin{bmatrix}
\times \\ \times 
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times \\ \times \\ \times
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times
\end{bmatrix}
$$

In [3]:
net = two_layer_net(2, 5, 3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [4]:
x = torch.Tensor([1, 1])
x

tensor([1., 1.])

In [5]:
p = net.forward(x)
p

tensor([0.4725, 0.3323, 0.1951], grad_fn=<SoftmaxBackward>)

### Syntactic easy for the forward method

In [6]:
p = net(x)
p

tensor([0.4725, 0.3323, 0.1951], grad_fn=<SoftmaxBackward>)

### Let's check that the probability vector indeed sum to `1`:

In [7]:
p.sum()

tensor(1.0000, grad_fn=<SumBackward0>)

### This network is composed of two Linear modules that we have called `layer1` and `layer2`. We can see this when we type:

In [8]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [9]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [10]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.5688,  0.6197],
        [ 0.6389,  0.4398],
        [-0.5295,  0.4641],
        [ 0.4410,  0.5070],
        [ 0.0921,  0.1703]], requires_grad=True)


In [11]:
print(net.layer1.bias)

Parameter containing:
tensor([ 0.6264, -0.4131,  0.0945,  0.1249, -0.1876], requires_grad=True)


### So to change the first row of the weights from `layer 1` you would do:

In [12]:
net.layer1.weight[0, 0] = 10
net.layer1.weight[0, 1] = 20

print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6389,  0.4398],
        [-0.5295,  0.4641],
        [ 0.4410,  0.5070],
        [ 0.0921,  0.1703]], grad_fn=<CopySlices>)


### Now we are going to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [13]:
p = net(x)
p

tensor([7.0214e-07, 1.0000e+00, 1.0958e-06], grad_fn=<SoftmaxBackward>)

### Alternatively, all the parameters of the network can be accessed by `net.parameters()`: 

In [14]:
list_of_params = list(net.parameters())
print(list_of_params)

[Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6389,  0.4398],
        [-0.5295,  0.4641],
        [ 0.4410,  0.5070],
        [ 0.0921,  0.1703]], grad_fn=<CopySlices>), Parameter containing:
tensor([ 0.6264, -0.4131,  0.0945,  0.1249, -0.1876], requires_grad=True), Parameter containing:
tensor([[-0.3866,  0.1247,  0.2236,  0.3814, -0.0721],
        [ 0.1174, -0.4074,  0.3799, -0.4263, -0.3139],
        [-0.3404, -0.1536,  0.1512, -0.2237, -0.0869]], requires_grad=True), Parameter containing:
tensor([ 0.0860,  0.0535, -0.0446], requires_grad=True)]
