# Lab 01 : Linear Module - Demo

In [1]:
import torch
import torch.nn as nn

### Make a Linear Module that takes input of size 5 and return output of size 3

In [2]:
mod = nn.Linear(5, 3)
mod

Linear(in_features=5, out_features=3, bias=True)

### Let's make a random tensor of size 5:

In [4]:
x = torch.rand(5)
x, x.size()

(tensor([0.3001, 0.6890, 0.6276, 0.2028, 0.7271]), torch.Size([5]))

### Feed it to the module:

In [6]:
y = mod(x)
y

tensor([0.7051, 0.0112, 0.2546], grad_fn=<AddBackward0>)

### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [7]:
print('weights:', mod.weight)

weights: Parameter containing:
tensor([[ 0.2388, -0.2528,  0.0423,  0.2701,  0.3878],
        [-0.4414,  0.2083, -0.3033,  0.4112,  0.2313],
        [ 0.3448,  0.3303,  0.1601,  0.2697,  0.0196]], requires_grad=True)


In [8]:
print('bias:', mod.bias)

bias: Parameter containing:
tensor([ 0.4443, -0.0611, -0.2458], requires_grad=True)


### If we want we can change the internal parameters of the module:

In [9]:
mod.weight[0, 0] = 0
mod.weight[0, 1] = 1
mod.weight[0, 2] = 2

print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.2701,  0.3878],
        [-0.4414,  0.2083, -0.3033,  0.4112,  0.2313],
        [ 0.3448,  0.3303,  0.1601,  0.2697,  0.0196]], grad_fn=<CopySlices>)


### We can also make a Linear module without bias:

In [10]:
mod2 = nn.Linear(5, 3, bias=False)
mod2

Linear(in_features=5, out_features=3, bias=False)

In [11]:
mod2.weight

Parameter containing:
tensor([[-0.0077, -0.4439, -0.2157,  0.3983, -0.4386],
        [ 0.3129, -0.3314, -0.0730,  0.1670, -0.1825],
        [ 0.0503,  0.3150, -0.4449, -0.0413, -0.2236]], requires_grad=True)

In [13]:
print(mod2.bias)

None
