## CE7454 : Deep Learning for Data Science
## Xavier Bresson


## Coding Test 1
Date: October 7th, 2020<br>

*Instructions* <br>
Name: Do not forget to add your name to the notebook file "coding_test1_CE7454_YOUR_NAME.ipynb".<br>
Questions: This notebook has 10 questions.<br>
Answers: Write the answers to each question in this notebook.<br>
Type: This test is individual and open-book.<br>
Grading: 1 point for each question.<br>
Delivery: Upload your notebook to https://drive.google.com/drive/folders/1Owos8IyA2Mh2PGvRlTEJZuNmR7sJOpx-  by 6:20pm. <br>
Remark: **If certain conditions of the questions (for eg. hyperparameter values) are not stated, you are free to choose anything you want.**<br>


### Question 1

Create a PyTorch tensor $x$ of type FloatTensor, size [5, 2, 7] and filled with random numbers. Print tensor $x$ and its type. Convert the same tensor $x$ to type LongTensor and print its value and type.

In [1]:
%reset -f
import torch

# YOUR CODE HERE
x = torch.FloatTensor(5, 2, 7).random_()
print("x is:")
print(x)
print("The type of x is:")
print(x.type())
print(" ")

x = x.long()
print("x is:")
print(x)
print("The type of x is:")
print(x.type())

x is:
tensor([[[11590729.,  9701815., 11257493., 16536800.,  9459967.,  3719045.,
          15422661.],
         [ 3587402.,  3625892.,  5021539.,  7802040., 10498097.,  7970677.,
          10642049.]],

        [[ 5167779., 14666898.,  2575403.,    60541., 14871767., 13804029.,
            890979.],
         [10664355.,  2160860., 12969401.,    85841., 12378694., 12349665.,
           8811207.]],

        [[ 3276918.,  7054158.,  6056577., 12423720., 10365456.,  8708237.,
           7544934.],
         [ 6647631.,  3300132.,  6892420.,  3983132.,  3206363.,   108060.,
            564177.]],

        [[14382251.,  5064879.,  2382149.,  8208201.,  5328591.,  6363700.,
          14156344.],
         [ 9001799.,  1592680., 10981261.,  5402074., 13383569., 10802019.,
           9434792.]],

        [[11522983.,   359172.,  4538727., 12086396.,  9029178.,  3124944.,
           8590923.],
         [13945835.,  4113668., 11464633.,  2919494., 12362805.,  4136984.,
          10967238.]]])
The 

### Question 2

Compute and print the matrix product of matrices A and B given below.

Compute and print the element-wise product of matrices C and D given below.


In [2]:
%reset -f
import torch

A=torch.ones(2,3)
B=torch.ones(3,2)
C=torch.ones(2,2)
D=torch.ones(2,2)

# YOUR CODE HERE
mat_product = torch.mm(A, B)
print("The matrix product of matrices A and B is:")
print(mat_product)
print(" ")

ele_product = torch.mul(C, D)
print("The element-wise product of matrices C and D is:")
print(ele_product)

The matrix product of matrices A and B is:
tensor([[3., 3.],
        [3., 3.]])
 
The element-wise product of matrices C and D is:
tensor([[1., 1.],
        [1., 1.]])


### Question 3

Given a minibatch $x$ of color images represented by a tensor of size (100, 3, 28, 28), with 3 color channels (red, green and blue), a grid domain of 28 pixels by 28 pixels, and 100 images in the minibatch. 

Transform the tensor $x$ into a vector and print its size.

Transform back the vector to a tensor of size (100, 3, 28, 28) and print its size.

In [3]:
%reset -f
import torch

x = torch.rand(100,3,28,28) # given minibatch of color images 

# YOUR CODE HERE
vec = x.numpy()
print(vec.shape)
print(vec.dtype)
print(" ")

tensor = torch.from_numpy(vec)
print(tensor.size())
print(tensor.dtype)

(100, 3, 28, 28)
float32
 
torch.Size([100, 3, 28, 28])
torch.float32


### Question 4

Consider a minibatch $s$ of scores of size (100,5) with 5 classes and 100 data points. Convert the scores into probabilities with the softmax operator. Print the scores and the probabilities for the 10th data point (reminder: 1st data point is indexed by 0). 

Implement a Python function that returns the indices of the classes corresponding to the highest probability for each data in the minibatch. Note that the 5 classes are indexed with integer values $\{0,1,2,3,4\}$. Print the index of the highest probability for the 10th data point.


In [4]:
%reset -f
import torch

s = torch.FloatTensor(100,5).uniform_(-1,5)

# YOUR CODE HERE
import torch.nn.functional as F

probs = F.softmax(s)
print("The scores for the 10th data point is:")
print(s[9])
print("The probabilities for the 10th data point is:")
print(probs[9])
print(" ")

def highest_prob_indice(s):
    probs = F.softmax(s)
    indice = probs.argmax(dim=1)
    return indice

print("The index of the highest probability for the 10th data point is:")
highest_prob_indice(s)[9]

The scores for the 10th data point is:
tensor([0.0360, 2.6953, 4.9182, 2.5561, 1.6402])
The probabilities for the 10th data point is:
tensor([0.0061, 0.0868, 0.8014, 0.0755, 0.0302])
 
The index of the highest probability for the 10th data point is:


/Users/dongdongdongdong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if __name__ == '__main__':
/Users/dongdongdongdong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


tensor(2)

### Question 5

Implement the activation function $$\sigma(x)=\frac{2}{2+e^{-x}}$$ as a Python function.

Print the activation values of the input tensor x1=$[-4.5,1.2,0.0,6.2]$ with function $\sigma$. 

Compute the analytical derivative of $\sigma$ and implement it as a Python function. 

$$\sigma'(x)=\textrm{to be computed}$$

Print the values of the input tensor x2=$[2.3,-1.9,-3.4,6.2]$ with function $\sigma'$.


In [5]:
%reset -f
import torch

x1 = torch.Tensor([-4.5,1.2,0.0,6.2])
x2 = torch.Tensor([2.3,-1.9,-3.4,6.2])

# YOUR CODE HERE
def activation_func(x):
    sigma  = 2 / (2 + torch.exp(-x))
    return sigma

print(activation_func(x1))

def derivative_func(x):
    partial_sigma = (2 * torch.exp(-x)) / (2 + torch.exp(-x))**2
    return partial_sigma

print(derivative_func(x2))

tensor([0.0217, 0.8691, 0.6667, 0.9990])
tensor([0.0455, 0.1772, 0.0587, 0.0010])


### Question 6

Implement a 2-layer MLP with the non-linear activation function $\sigma$ from Question 5. The output score of the network is defined as

$$s = W_2\sigma(W_1 x + b_1)+b_2$$

The size of tensor $x$ is 2 and the size of tensor $s$ is 3.

Tensor $W_1$ is a matrix of ones and size (10,2) and tensor $W_2$ is a matrix of ones and size (3,10). 

Tensors $b_1$ and $b_2$ are vectors of zeros with their sizes constrained by $W_1$ and $W_2$.

Print the output tensor $s$ for the input $x=[2.3,-1.4]$. 

In [9]:
%reset -f
import torch
import torch.nn as nn

x = torch.Tensor([2.3,-1.4])

# YOUR CODE HERE

def activation_func(x):
    sigma  = 2 / (2 + torch.exp(-x))
    return sigma

W1 = torch.ones(10, 2)
W2 = torch.ones(3, 10)
b1 = torch.zeros(1, 10)
b2 = torch.zeros(1, 3)


def two_layer_mlp(x):
    x = x.view(1, -1)
    h = activation_func(x @ W1.T + b1)
    h = h @ W2.T + b2
    return h

s = two_layer_mlp(x)
print(s)

tensor([[8.3106, 8.3106, 8.3106]])


### Question 7

Given a minibatch $s=[ [5.2,-1.2], [-1.0,4.0], [-1,2] ]$ of scores of three data points and two classes, implement and compute the mean cross entropy for the labels $[0,1,1]$.

As a reminder, the definition of the mean cross entropy loss is 

$$ L = -\frac{1}{N}\sum_{i=1}^N \log \Big(\textrm{entry cl($i$) of probability vector } p^{(i)} \Big)$$

where $cl($i$)$ is the class index of the $i^{th}$ training data and $p^{(i)}$ is the probability vector computed by the network (using the score vector).

Note that your implementation of the cross entropy cannot use the PyTorch function 'nn.CrossEntropyLoss'. 

In [19]:
%reset -f
import torch
import torch.nn as nn

s = torch.Tensor( [ [5.2,-1.2], [-1.0,4.0], [-1,2] ] )
label = torch.LongTensor([0,1,1])

# YOUR CODE HERE
import numpy as np

def cross_entropy_loss(s, label):
    logSoftmax = -torch.log_softmax(s, dim=-1)
    entropy = torch.gather(logSoftmax, dim=-1, index=label.view(-1, 1))
    return entropy.mean()


cross_entropy_loss(s, label)

tensor(0.0190)

### Question 8

Implement a new class for the sigma function $\sigma$ defined in Question 5. Precisely, define explicitely the forward pass and the backward pass for this new class. Hint: https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

Print the output value $y=\sigma(x)$ for the tensor $x=[1.6,-1.2,0.0,4.0]$.

Consider the loss to be 

$$ L = \frac{1}{m}\sum_{j=1}^m y_j^2,\quad y_j=\sigma(x_j)$$

where $x_1=1.6, x_2=-1.2, x_3=0.0, x_4=4.0$.

Print the gradient value $\frac{dL}{dx}$ for $x=[1.6,-1.2,0.0,4.0]$.


In [ ]:
%reset -f
import torch

x = torch.Tensor([1.6,-1.2,0.0,4.0])

# YOUR CODE HERE

class MySigma(torch.autograd.Function):

    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input


### Question 9

Implement a class of 3-layer MLP with ReLU activation :

$$s = W_3\textrm{ ReLU}(W_2\textrm{ ReLU}(W_1 x + b_1)+b_2)+b_3)$$

Instantiate a network with 784 as input dimension, 50 as hidden dimension and 10 as output dimension.

During training, only the last linear layer will be trained (the first two linear layers will not be trained and will keep the same initial values during training). 

Use 10 epochs to train the network with batch size 100 and learning rate 0.01. Print the loss and error of classification of the training set after 10 epochs.

In [18]:
%reset -f
import torch
import torch.nn as nn
from utils import *
data_path=check_mnist_dataset_exists()
train_data=torch.load(data_path+'mnist/train_data.pt')
train_label=torch.load(data_path+'mnist/train_label.pt')

# YOUR CODE HERE
import torch.nn.functional as F
import utils
import time

data_path = "/Users/dongdongdongdong/Desktop/data/mnist"
train_data = torch.load(data_path + "/train_data.pt")
train_label = torch.load(data_path + "/train_label.pt")
test_data = torch.load(data_path + "/test_data.pt")
test_label = torch.load(data_path + "/test_label.pt")

class three_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size1, hidden_size2,  output_size):
        super(three_layer_net , self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size1  , bias=False  )
        self.layer2 = nn.Linear(hidden_size1, hidden_size2  , bias=False  )
        self.layer3 = nn.Linear(hidden_size2, output_size   , bias=False  )        
        
    def forward(self, x):
        
        y       = self.layer1(x)
        y_hat   = F.relu(y)
        z       = self.layer2(y_hat)
        z_hat   = F.relu(z)
        scores  = self.layer3(z_hat)
        return scores
    
    
net = three_layer_net(784, 50, 50, 10)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

bs = 100

start = time.time()

for epoch in range(10):
    
    running_loss = 0
    running_error = 0
    num_batches = 0
    
    shuffled_indices = torch.randperm(60000)
    
    for i in range(0, 60000, bs):
        
        # forward and backward pass
        optimizer.zero_grad()
        
        indices = shuffled_indices[i : i+bs]
        minibatch_data = train_data[indices]
        minibatch_labels = train_label[indices]
        
        inputs = minibatch_data.view(bs, -1)
        inputs.requires_grad_()
        
        scores = net(inputs)
        loss = criterion(scores, minibatch_labels)
        loss.backward()
        optimizer.step()
        
        # compute some stats
        running_loss += loss.detach().item()
        error = utils.get_error(scores.detach(), minibatch_labels)
        running_error += error
        num_batches += 1
        
    # once the epoch is finished we divide the "running quantities"
    # by the number of batches
    total_loss = running_loss / num_batches
    total_error = running_error / num_batches
    elapsed_time = time.time() - start
    
    print(" ")
    print("Epoch: {}, Time: {}, Loss: {}, Error: {}%".format(
            epoch, elapsed_time, total_loss, total_error*100))

 
Epoch: 0, Time: 0.682826042175293, Loss: 2.1406923085451126, Error: 65.5967025756836%
 
Epoch: 1, Time: 1.5185980796813965, Loss: 1.0552668581406275, Error: 24.373321533203125%
 
Epoch: 2, Time: 2.2595200538635254, Loss: 0.5684860005478064, Error: 15.8416748046875%
 
Epoch: 3, Time: 3.2895851135253906, Loss: 0.4580908886839946, Error: 13.09499740600586%
 
Epoch: 4, Time: 4.158290147781372, Loss: 0.40200625131527584, Error: 11.433338165283203%
 
Epoch: 5, Time: 4.83431601524353, Loss: 0.3657472025106351, Error: 10.488338470458984%
 
Epoch: 6, Time: 5.464990139007568, Loss: 0.3403247091174126, Error: 9.775003433227539%
 
Epoch: 7, Time: 6.1218202114105225, Loss: 0.32052154836555324, Error: 9.190007209777832%
 
Epoch: 8, Time: 6.9768030643463135, Loss: 0.304632725790143, Error: 8.685013771057129%
 
Epoch: 9, Time: 7.694217920303345, Loss: 0.2912266111373901, Error: 8.318340301513672%


### Question 10

Use the class of 3-layer MLP with ReLU activation implemented in Question 9. 

We will train the network with the quality loss defined as

$$ L = \Big( \Pi_{i=1}^N \textrm{entry cl($i$) of probability vector } p^{(i)} \Big)^{1/N}$$

where $cl($i$)$ is the class index of the $i^{th}$ training data and $p^{(i)}$ is the probability vector computed by the network.

Unlike Question 9, all linear layers will be learned during training. 

Use 10 epochs to train the network with batch size 25 and learning rate 0.01. Print the loss and error of classification of the training set after 10 epochs.


In [16]:
%reset -f
import torch
import torch.nn as nn
from utils import *
data_path=check_mnist_dataset_exists()
train_data=torch.load(data_path+'mnist/train_data.pt')
train_label=torch.load(data_path+'mnist/train_label.pt')

# YOUR CODE HERE
import torch.nn.functional as F
import utils
import time

data_path = "/Users/dongdongdongdong/Desktop/data/mnist"
train_data = torch.load(data_path + "/train_data.pt")
train_label = torch.load(data_path + "/train_label.pt")
test_data = torch.load(data_path + "/test_data.pt")
test_label = torch.load(data_path + "/test_label.pt")

class three_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size1, hidden_size2,  output_size):
        super(three_layer_net , self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size1  , bias=False  )
        self.layer2 = nn.Linear(hidden_size1, hidden_size2  , bias=False  )
        self.layer3 = nn.Linear(hidden_size2, output_size   , bias=False  )        
        
    def forward(self, x):
        
        y       = self.layer1(x)
        y_hat   = F.relu(y)
        z       = self.layer2(y_hat)
        z_hat   = F.relu(z)
        scores  = self.layer3(z_hat)
        return scores
    
net = three_layer_net(784, 50, 50, 10)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

bs = 25

start = time.time()

for epoch in range(10):
    
    running_loss = 0
    running_error = 0
    num_batches = 0
    
    shuffled_indices = torch.randperm(60000)
    
    for i in range(0, 60000, bs):
        
        # forward and backward pass
        optimizer.zero_grad()
        
        indices = shuffled_indices[i : i+bs]
        minibatch_data = train_data[indices]
        minibatch_labels = train_label[indices]
        
        inputs = minibatch_data.view(bs, -1)
        inputs.requires_grad_()
        
        scores = net(inputs)
        loss = criterion(scores, minibatch_labels)
        loss.backward()
        optimizer.step()
        
        # compute some stats
        running_loss += loss.detach().item()
        error = utils.get_error(scores.detach(), minibatch_labels)
        running_error += error
        num_batches += 1
        
    # once the epoch is finished we divide the "running quantities"
    # by the number of batches
    total_loss = running_loss / num_batches
    total_error = running_error / num_batches
    elapsed_time = time.time() - start
    
    print(" ")
    print("Epoch: {}, Time: {}, Loss: {}, Error: {}%".format(
            epoch, elapsed_time, total_loss, total_error*100))

 
Epoch: 0, Time: 1.762186050415039, Loss: 1.0382851350990434, Error: 30.66142463684082%
 
Epoch: 1, Time: 3.907280206680298, Loss: 0.36420674024925875, Error: 10.476632118225098%
 
Epoch: 2, Time: 6.0850749015808105, Loss: 0.30479738157708197, Error: 8.728317260742188%
 
Epoch: 3, Time: 8.055040121078491, Loss: 0.2651481191907078, Error: 7.636672019958496%
 
Epoch: 4, Time: 10.018212080001831, Loss: 0.23385957193677315, Error: 6.626687049865723%
 
Epoch: 5, Time: 12.03337025642395, Loss: 0.20848984520727148, Error: 5.906722545623779%
 
Epoch: 6, Time: 14.009705066680908, Loss: 0.18902616363329192, Error: 5.3834123611450195%
 
Epoch: 7, Time: 16.114185094833374, Loss: 0.17243741815560498, Error: 4.93173885345459%
 
Epoch: 8, Time: 18.112970113754272, Loss: 0.15846718902078769, Error: 4.5367326736450195%
 
Epoch: 9, Time: 20.028197050094604, Loss: 0.14659617592425397, Error: 4.20172643661499%
